# action.yml
name: 'create index and quick start from pyproject.toml'
description: 'Provided a pyproject.toml file create a markdown index and quick start page'
inputs:
  src-file: 
    description: 'path to the pyproject.toml'
    required: true
    default: 'pyproject.toml'
  out-file-index: 
    description: 'path to the generated index file'
    required: true
    default: 'docs/index.md'
  out-file-quick:
    description: 'path to the generated quick_start file'
    required: true
    default: 'docs/quick_start.md'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src-file }}
    - ${{ inputs.out-file-index }}
    - ${{ inputs.out-file-quick }}